language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://will-poc.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "tqNHGtdPDdk2xgrsMiYxduib9/1u7Bsmeuv8oAjipEI7/6lbmeWRfhxTV8F0Xm5fAY3lHn2jRfKPdVCLmm2JgavRcvjE7DqebSiUT5hX++E2MZrX0semhVGS/Pm2os9/9k+kZUqxI2Vg2E85jlVW9v7ysTXdwRcsN8EtlqYKzXd0YiSOliL26Ab8TFvvEYDNnZTd+WEljEdsaGXdest6kKSp61MO4AzeysIPFWhkym0EekIjgeMyJ2QhFJui6h8cJg0CV0cevgd962Yk7iRL+1ENSLzXEMli58wGZeLBKZ/M59PchL44c3v8R+x84zEYiuYvnRahQ1PtM823bg5n1ZUvzzoCOT1Bcjg87dTptsGFHCujLezPbiLH672JO6G/+TlZd4C0mlwvM8dT9Cho7haKOzHndUrHh6PLsnp0bJoCyZqB5XLSGkKbG2ZTvGgsjmkRejwRNg6yVl9KhUkQDex7CXGXrjbNlN/dQ65WjYJR5GiuZiSog0piv3aWkH/J7ccHzdq4+5rpBieYb/9xVki1vNEPt067lpHJkKhe0l/DgpUci9CLFryYcE6kb+64ro0WH+fdQeuL1v3s3RA/G7h0VMpMboSp1RGcSvSwI8mQFh02BHb+vEJgiLslLYOC8wwzebpFjhlOtioZzr2D7wAmPpq9P1OnMK+D/JvKqDw="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
